void marco(int x, int y, int width, int height);
void estetica(void);
void focus(int focus, int cond);
void creditos(void);
void marcoInventario(int color, int borderColor);
void marcoAyuda(int color, int borderColor);
void marcoServicio(int color, int borderColor);
void marcoGanancias(int color, int borderColor);
void marcoError(void);
void outputSection(int focused);
void inventarioItem1(int color);
void inventarioItem2(int color);
void inventarioItem3(int color);
void inventarioItem4(int color);
void inventarioItem5(int color);
void inventarioItem6(int color);
void servicioItem1(int color);
void servicioItem2(int color);
void servicioItem3(int color);
void servicioItem4(int color);
void servicioItem5(int color);
void servicioItem6(int color);
